In [116]:
import pandas as pd
import numpy as np


In [117]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [119]:
df.duplicated().sum()

0

In [120]:
df.corr()["Outcome"]

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [121]:
X = df.iloc[:,:-1]
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [122]:
y = df.iloc[:,-1]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [123]:
from sklearn.preprocessing import StandardScaler

In [124]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [125]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [126]:
X.shape

(768, 8)

In [127]:
import sklearn
from sklearn.model_selection import train_test_split

In [128]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=1)

In [129]:
X_train

array([[ 1.53084665,  0.75443236,  0.56322275, ...,  0.74976553,
         0.49869316,  0.57511787],
       [ 1.82781311,  0.25367803, -0.36733675, ...,  1.16859904,
        -0.0932501 ,  0.40494237],
       [ 0.93691372, -0.59134489,  0.25303625, ...,  0.66092205,
        -0.80901822,  1.00055664],
       ...,
       [ 2.7187125 ,  0.1597866 ,  1.08020025, ...,  1.44782138,
         0.33560676,  0.74529338],
       [ 0.04601433,  1.56815814,  0.14964075, ...,  1.47320522,
         0.02151441, -0.61611067],
       [ 1.53084665, -0.59134489,  0.35643175, ...,  0.1151693 ,
         0.58325649,  1.08564439]])

In [130]:
X_test

array([[ 0.93691372,  0.47275805,  0.25303625, ..., -0.76057349,
         0.52889435,  1.51108316],
       [-0.84488505,  0.94221523, -0.47073225, ..., -0.74788157,
        -0.88452119, -0.95646168],
       [ 0.63994726, -0.37226487, -0.47073225, ..., -0.88749274,
        -0.80297799, -0.53102292],
       ...,
       [ 1.23388019,  2.10020961,  0.45982725, ...,  2.01895798,
        -1.01136617,  0.83038113],
       [ 0.3429808 ,  0.47275805,  0.66661825, ..., -4.06047387,
         0.50775352,  3.04266271],
       [ 0.04601433, -0.96691063, -3.57259724, ..., -0.506735  ,
         0.41714996, -0.19067191]])

In [131]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [132]:
model = Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation = 'sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [133]:
model.fit(X_train,y_train,batch_size=32,epochs=100, validation_data=(X_test,y_test))

Epoch 1/100
20/20 [==============================] - 1s 20ms/step - loss: 0.6986 - accuracy: 0.5537 - val_loss: 0.6574 - val_accuracy: 0.6883
Epoch 2/100
20/20 [==============================] - 0s 8ms/step - loss: 0.6338 - accuracy: 0.6922 - val_loss: 0.6042 - val_accuracy: 0.7273
Epoch 3/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5900 - accuracy: 0.7248 - val_loss: 0.5651 - val_accuracy: 0.7532
Epoch 4/100
20/20 [==============================] - 0s 9ms/step - loss: 0.5555 - accuracy: 0.7459 - val_loss: 0.5385 - val_accuracy: 0.7662
Epoch 5/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5321 - accuracy: 0.7557 - val_loss: 0.5171 - val_accuracy: 0.7857
Epoch 6/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5142 - accuracy: 0.7687 - val_loss: 0.5006 - val_accuracy: 0.7922
Epoch 7/100
20/20 [==============================] - 0s 8ms/step - loss: 0.5013 - accuracy: 0.7622 - val_loss: 0.4876 - val_accuracy: 0.7792
Epoch 8/100


In [134]:
# 1. how to select appropriate optimizer
# 2. No of nodes in a layer
# 3. How to select no. of layers
# 4. All in all one model

In [135]:
!pip install -U keras-tuner

In [136]:
import keras_tuner as kt


In [147]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu', input_dim = 8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer = hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer = optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model


In [148]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json


In [149]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


In [158]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [154]:
best_model = tuner.get_best_models()[0]
best_model


In [155]:
best_model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321 (1.25 KB)
Trainable params: 321 (1.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [160]:
model.fit(X_train,y_train,batch_size=32,epochs=100, initial_epoch =6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 [==============================] - 0s 16ms/step - loss: 0.4171 - accuracy: 0.7997 - val_loss: 0.4536 - val_accuracy: 0.7922
Epoch 8/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4162 - accuracy: 0.8013 - val_loss: 0.4535 - val_accuracy: 0.7922
Epoch 9/100
20/20 [==============================] - 0s 10ms/step - loss: 0.4165 - accuracy: 0.7997 - val_loss: 0.4547 - val_accuracy: 0.7792
Epoch 10/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4158 - accuracy: 0.7948 - val_loss: 0.4542 - val_accuracy: 0.7922
Epoch 11/100
20/20 [==============================] - 0s 10ms/step - loss: 0.4154 - accuracy: 0.8046 - val_loss: 0.4546 - val_accuracy: 0.7857
Epoch 12/100
20/20 [==============================] - 0s 10ms/step - loss: 0.4145 - accuracy: 0.7997 - val_loss: 0.4525 - val_accuracy: 0.7922
Epoch 13/100
20/20 [==============================] - 0s 8ms/step - loss: 0.4146 - accuracy: 0.8029 - val_loss: 0.4522 - val_accuracy: 0.7922
Epoch

In [162]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units',8,128,step=8)

  model.add(Dense(units=units, activation = 'relu', input_dim = 8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

In [163]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials =5)

Reloading Tuner from ./untitled_project/tuner0.json


In [164]:
tuner.search(X_train,y_train,epochs=5, validation_data = (X_test,y_test))

In [168]:
def build_model(hp):
  model = Sequential()

  units = hp.Int('units',8,128,step=8)

  model.add(Dense(units=units, activation = 'relu', input_dim = 8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model

In [170]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials =5,
                        directory = 'mydir',
                        project_name = 'khush')

In [171]:
tuner.search(X_train,y_train,epochs=5, validation_data = (X_test,y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.6688311696052551

Best val_accuracy So Far: 0.798701286315918
Total elapsed time: 00h 00m 13s


In [175]:
tuner.get_best_hyperparameters()[0].values

{'units': 112}

In [176]:
model = tuner.get_best_models()[0]

In [179]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6)


Epoch 7/100
20/20 [==============================] - 1s 4ms/step - loss: 0.5067 - accuracy: 0.7687
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4868 - accuracy: 0.7736
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4750 - accuracy: 0.7785
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4667 - accuracy: 0.7736
Epoch 11/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4615 - accuracy: 0.7752
Epoch 12/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4567 - accuracy: 0.7818
Epoch 13/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4542 - accuracy: 0.7818
Epoch 14/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4506 - accuracy: 0.7818
Epoch 15/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4485 - accuracy: 0.7801
Epoch 16/100
20/20 [==============================] - 0s 4ms/step - loss: 0.4468 - accuracy: 0.7801
Epo

In [184]:
def build_model(hp):

  model = Sequential()

  model.add(Dense(72,activation = 'relu', input_dim = 8))

  for i in range(hp.Int('num_layers', min_value = 1, max_value=10)):
    model.add(Dense(72,activation='relu'))

  model.add(Dense(1,activation = 'sigmoid'))

  model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
  return model


In [185]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name = 'num_layers'
                        )

In [186]:
tuner.search(X_train,y_train,epochs=5, validation_data = (X_test,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 13s


In [188]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4}

In [195]:
model = tuner.get_best_models()[0]

In [196]:
model

In [199]:
model.fit(X_train,y_train, batch_size = 32, epochs = 100, initial_epoch = 6 , validation_data = (X_test, y_test))

Epoch 7/100
20/20 [==============================] - 2s 15ms/step - loss: 0.4251 - accuracy: 0.7915 - val_loss: 0.4545 - val_accuracy: 0.7922
Epoch 8/100
20/20 [==============================] - 0s 7ms/step - loss: 0.4289 - accuracy: 0.7948 - val_loss: 0.4414 - val_accuracy: 0.8117
Epoch 9/100
20/20 [==============================] - 0s 6ms/step - loss: 0.4048 - accuracy: 0.8127 - val_loss: 0.4335 - val_accuracy: 0.8247
Epoch 10/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3938 - accuracy: 0.8176 - val_loss: 0.4382 - val_accuracy: 0.8052
Epoch 11/100
20/20 [==============================] - 0s 10ms/step - loss: 0.3876 - accuracy: 0.8225 - val_loss: 0.4425 - val_accuracy: 0.8052
Epoch 12/100
20/20 [==============================] - 0s 13ms/step - loss: 0.3802 - accuracy: 0.8274 - val_loss: 0.4534 - val_accuracy: 0.8117
Epoch 13/100
20/20 [==============================] - 0s 10ms/step - loss: 0.3655 - accuracy: 0.8404 - val_loss: 0.4592 - val_accuracy: 0.8052
Epoch