In [1]:
import numpy as np

docs = ['go pakistan',
		'pakistan pakistan',
		'hip hip hurray',
		'jeetega bhai jeetega pakistan jeetega',
		'pakistan is the best country',
		'baber azam baber azam',
		'hafiz hafiz',
		'haris haris',
		'pakistan is the best country',
		'pakistan zindabad']

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

In [3]:
tokenizer.word_index

{'pakistan': 1,
 'jeetega': 2,
 'hip': 3,
 'is': 4,
 'the': 5,
 'best': 6,
 'country': 7,
 'baber': 8,
 'azam': 9,
 'hafiz': 10,
 'haris': 11,
 'go': 12,
 'hurray': 13,
 'bhai': 14,
 'zindabad': 15}

In [4]:
len(tokenizer.word_index)

15

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[12, 1],
 [1, 1],
 [3, 3, 13],
 [2, 14, 2, 1, 2],
 [1, 4, 5, 6, 7],
 [8, 9, 8, 9],
 [10, 10],
 [11, 11],
 [1, 4, 5, 6, 7],
 [1, 15]]

In [6]:
from keras.utils import pad_sequences

In [7]:
 sequences = pad_sequences(sequences, padding = 'post')
 sequences

array([[12,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 13,  0,  0],
       [ 2, 14,  2,  1,  2],
       [ 1,  4,  5,  6,  7],
       [ 8,  9,  8,  9,  0],
       [10, 10,  0,  0,  0],
       [11, 11,  0,  0,  0],
       [ 1,  4,  5,  6,  7],
       [ 1, 15,  0,  0,  0]], dtype=int32)

In [8]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [9]:
model = Sequential()
model.add(Embedding(17, output_dim = 2, input_length = 5))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.compile('adam', 'accuracy')

In [11]:
pred  = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 381ms/step
[[[-0.00818986  0.01539013]
  [ 0.04297738  0.00813513]
  [-0.04254601  0.02742196]
  [-0.04254601  0.02742196]
  [-0.04254601  0.02742196]]

 [[ 0.04297738  0.00813513]
  [ 0.04297738  0.00813513]
  [-0.04254601  0.02742196]
  [-0.04254601  0.02742196]
  [-0.04254601  0.02742196]]

 [[-0.02595567 -0.007477  ]
  [-0.02595567 -0.007477  ]
  [ 0.00854075  0.01622626]
  [-0.04254601  0.02742196]
  [-0.04254601  0.02742196]]

 [[-0.00933368  0.03044811]
  [-0.00856725  0.04527814]
  [-0.00933368  0.03044811]
  [ 0.04297738  0.00813513]
  [-0.00933368  0.03044811]]

 [[ 0.04297738  0.00813513]
  [ 0.04268006 -0.0231315 ]
  [-0.02660575  0.01220173]
  [ 0.01319773 -0.03849188]
  [-0.04688428 -0.00034096]]

 [[ 0.0128736  -0.01270508]
  [ 0.01147686 -0.01333088]
  [ 0.0128736  -0.01270508]
  [ 0.01147686 -0.01333088]
  [-0.04254601  0.02742196]]

 [[ 0.0209391  -0.0437774 ]
  [ 0.0209391  -0.0437774 ]
  [-0.04254601  0.02742196]
  [-0.04254

In [12]:
from keras.datasets import imdb
from keras.layers import Embedding,SimpleRNN,Dense,Flatten

In [13]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [14]:
X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

In [15]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [16]:
X_train  = pad_sequences(X_train, padding = 'post', maxlen = 50)
X_test  = pad_sequences(X_test, padding = 'post', maxlen = 50)

In [17]:
len(X_train)

25000

In [18]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [19]:
len(X_train[0])

50

In [20]:
len(X_train[1])

50

In [21]:
len(X_train[2])

50

In [22]:
X_train.shape

(25000, 50)

In [23]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

# Create a Sequential model
model = Sequential()

# Add an Embedding layer
# input_dim=10000: The size of the vocabulary (10,000 unique words/tokens)
# output_dim=2: The size of the embedding vector for each word/token
# input_length=50: The length of the input sequences
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))

# Add a SimpleRNN layer
# 32: Number of units in the RNN layer
# return_sequences=False: The RNN layer will output the last hidden state only
model.add(SimpleRNN(32, return_sequences=False))

# Add a Dense layer
# 1: Number of units in the Dense layer
# activation='sigmoid': Activation function for the Dense layer, suitable for binary classification
model.add(Dense(1, activation='sigmoid'))

# Print the model summary to see the architecture of the model
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 79s 98ms/step - loss: 0.5921 - accuracy: 0.6583 - val_loss: 0.4313 - val_accuracy: 0.8035
Epoch 2/5
782/782 [==============================] - 46s 59ms/step - loss: 0.3832 - accuracy: 0.8333 - val_loss: 0.4161 - val_accuracy: 0.8157
Epoch 3/5
782/782 [==============================] - 46s 59ms/step - loss: 0.3201 - accuracy: 0.8693 - val_loss: 0.4550 - val_accuracy: 0.7879
Epoch 4/5
782/782 [==============================] - 47s 59ms/step - loss: 0.2860 - accuracy: 0.8856 - val_loss: 0.4839 - val_accuracy: 0.7991
Epoch 5/5
782/782 [==============================] - 47s 60ms/step - loss: 0.2542 - accuracy: 0.9027 - val_loss: 0.5025 - val_accuracy: 0.7948
